### ISSUE TITLE
C# to Dart Transpiler

### ISSUE THREAD

**Issue by rredoh** [adamped/xamarin.flutter#16]
Hi Adam. It's nice to see your effort. I'm a newbie Xamarin developer, and have come across your website and there. And I have read about some flutter stuff. And I found something here. I found some [C# to Dart transpiler tools.](https://www.microsoft.com/en-us/p/c-to-dart-transpiler/9p5bnfrsmq00?activetab=pivot:overviewtab)
Maybe if it could help this work. Good luck and keep up the good work Adam 👍 :)

**Comment by adamped** [comment]
Unfortunately the wrong way around for what we need. We are building a Dart to C# transpiler :) Thanks.

**Comment by rredoh** [comment]
Ah. Okay then. My mistake. I'm sorry..
