### ISSUE TITLE
Errors running the transpiler

### ISSUE THREAD

**Issue by JeroMiya** [adamped/xamarin.flutter#35]
Just tried this yesterday. Got this error while running analyzer.dart:
`
C:\Users\JBell\Downloads\xamarin.flutter-master\xamarin.flutter-master\flutter\lib\src\packages\flutter_tools\lib\src\base\logger.dart
Unhandled exception:
NoSuchMethodError: The getter 'childEntities' was called on null.
Receiver: null
Tried calling: childEntities
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      Implementation.processMethodInvocation (file:///C:/Users
`

Also got a few "ouch" messages along the way:

```
C:\Users\JBell\Downloads\xamarin.flutter-master\xamarin.flutter-master\flutter\lib\src\packages\flutter\lib\src\rendering\platform_view.dart
ouch
ouch
```

```
C:\Users\JBell\Downloads\xamarin.flutter-master\xamarin.flutter-master\flutter\lib\src\packages\flutter\lib\src\widgets\platform_view.dart
ouch
ouch
```

**Comment by adamped** [comment]
We are currently in progress of trying to get our first working version. We don't even have a working alpha version yet, so nothing complete, and you will come across heaps of errors everywhere. It's not quite ready for people to test out just yet.
